# Generated by Django 4.2 on 2024-09-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('topic', models.CharField(max_length=120)),
                ('no_of_questions', models.IntegerField()),
                ('time', models.IntegerField(help_text='duration of the quiz')),
                ('req_score_to_pass', models.IntegerField(help_text='score to pass')),
            ],
        ),
    ]
