# Generated by Django 4.2 on 2024-08-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_module'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Module',
            new_name='Materials',
        ),
    ]
